# k8s/sidecar-demo.yaml

apiVersion: v1
kind: Pod
metadata:
  name: mc1
spec:
  containers:
    - name: webserver
      image: nginx
      volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
    - name: helper
      image: debian
      volumeMounts:
      - name: html
        mountPath: /html
      command: ["/bin/sh", "-c"]
      args:
        - while true; do
            date >> /html/index.html;
            sleep 1;
          done
  volumes:
    - name: html
      emptyDir: {}