apiVersion: v1
kind: Secret
metadata:
  name: dockerhub
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth": "YWxleGV5bWloYXlsba3ZkZXZAZ21haWwuY29tOlphcDE0MTQxNCE="
        }
      }
    }


# echo -n 'username:password' | base64    -----> YWxleGV5bWloYXlsba3ZkZXZAZ21haWwuY29tOlphcDE0MTQxNCE