apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.releaseName }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.releaseName }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: {{ .Values.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Values.releaseName }}
    spec:
      containers:
        - name: {{ .Values.releaseName }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.containerPort }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
