apiVersion: v1
kind: Pod
metadata:
    name: react-site-demo-pod
spec:
    containers:
    - name: react-site-kuber-container
      image: alexeymihaylovdev/demo:1.1
      ports:
      - containerPort: 80


# kubectl apply -f k8s/pods/nginx.yaml  
# kubectl get pod nginx-pod -o yaml
# kubectl describe pod nginx-pod
# kubectl port-forward nginx-pod 8080:80
# kubectl logs nginx-pod
# kubectl delete pod nginx-pod
