apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: all-permissions
rules:
- apiGroups: ["*"]  # all groups
  resources: ["*"]  # all resources
  verbs: ["*"]  # all verbs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-nginx
subjects:
- kind: ServiceAccount
  name: default
  namespace: ingress-nginx