apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hosts
spec:
  rules:
  - host: www.aba-babala2.co.il            
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: react-site-service
            port:
              number: 80